export const ACTION = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_EMPLOYEES: "GET_EMPLOYEES",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
};
